### ISSUE TITLE
关于 cache 的 expire 问题

### ISSUE THREAD

**Issue by gouchaoer** [swoft-cloud/swoft-cache#1]
我有类似的疑惑，swoft可否考虑一下我的想法：
https://www.v2ex.com/t/431234#reply14
姑且称之为single flight缓存，策略如下：

每个缓存key都伴随了一个key_exp，当从数据库查到结果去设置key对应的缓存的时候，就同时设置一个expire超时的key_exp（当然了如果key_exp存在就设置失败）；每次去取key对应的缓存的时候，如果key没有数据就说明需要更新缓存了；如果key有数据，就尝试去设置一个expire超时的key_exp（当然了如果key_exp存在就设置失败），如果设置成功就说明需要更新缓存了；

说到底就是你要更新缓存就要么key下没有数据，或者要获取一把超时时间为expire的锁，才能更新缓存。

我们假设把缓存分成redis/memcached之类的有io开销的分布式缓存、apcu/swoole table这种基于共享内存的单机缓存以及worker内部的应用缓存，这3类都可以用得到的

**Comment by stelin** [comment]
这个限制功能，我觉得不应该由框架来做，应该按照业务需求实现。
